### ISSUE TITLE
EventSource is not supported by IE

### ISSUE THREAD

**Issue by rleir** [gctools-outilsgc/gcdashboard#1]
In IE you see a black screen, possibly because this is in application.js, about line 15009:
```

  source = new EventSource('events');

  source.addEventListener('open', function(e) {
    return console.log("Connection opened", e);
  });

  source.addEventListener('error', function(e) {
    console.log("Connection error", e);
    if (e.currentTarget.readyState === EventSource.CLOSED) {
```

**Comment by markwooff** [comment]
Hi @rleir, I remember I had looked into adding an IE polyfill for EventSource a while back without success. I've just updated this and also changed the `X-UA-Compatible` to `edge`. Unfortunately this doesn't seem to fix the issue on IE.

**Comment by rleir** [comment]
Smashing is looking to fix this. Let's put this issue on hold until Smashing has fixed it.
https://github.com/Smashing/smashing/issues/34

**Comment by markwooff** [comment]
Could you try loading http://stats.gctools.ca on your IE? I just added some hacks which may fix the issue.

**Comment by terraboops** [comment]
@rleir - this fix is really really really low on our priorities... FYI

**Comment by rleir** [comment]
@markwooff  SCRIPT65535: Invalid calling object File: application.js, Line: 1884, Column: 5

@tylermauthe I use Chrome, and avoid IE. But most GC users are on IE. Maybe I can fix it.

Thanks Mark, Tyler

**Comment by Troy-Lawson** [comment]
closing as we wont fix
